- name: Run Updates
  apt:
    update_cache: yes
  become: true

- name: Upgrade
  apt:
    upgrade: yes
    update_cache: yes
  become: true

- name: update before installing the needed software
  apt:
    update_cache: yes
  become: true